### ISSUE TITLE
Could not find method parseComponent() for arguments [project ':runtime/component/moqui-elasticsearch'] on project ':runtime/component/moqui-elasticsearch'.

### ISSUE THREAD

**Issue by sskmail14** [moqui/moqui-elasticsearch#1]
@jonesde 
Added the below line in addons.xml
`<component name="moqui-elasticsearch" group="moqui" version="" branch="master" repository="github"/>`

Once after downloading the command with  
`./gradlew getComponent -Pcomponent=moqui-elasticsearch`

After that I try to build with `gradlew build` am getting the below exception

> Could not find method parseComponent() for arguments [project ':runtime/component/moqui-elasticsearch'] on project ':runtime/component/moqui-elasticsearch'.

**Comment by jonesde** [comment]
Are you using an older version of moqui-framework? In general when getting the latest from the git repository for any component you need the latest from the git repository for moqui-framework as well.

Which version of moqui-framework are you using and how did you download it?

**Comment by sskmail14** [comment]
We have started developing the project in version 1.6.1 before six months. So changing to the new version of 2.0.0 is quite difficult. Kindly guide me to get through this issue in version 1.6.1.

**Comment by jonesde** [comment]
The solution is easy: don't use the moqui-elasticsearch component at all. In previous releases ElasticSearch was included in the framework and was not a separate component.

**Comment by sskmail14** [comment]
Ok thank you for the information.
As per your comments I will go for the elasticsearch which is in `<MOQUI_ROOT>\runtime\elasticsearch`

I have pulled some data into the elasticsearch using [Moqui-JDBC Connector
](https://github.com/jprante/elasticsearch-jdbc) from MySQL DB but I doesn't know how to fetch it using Moqui.

My question is quite simple `"How do I fetch the data using Moqui(CRUD is also ok)?"` - as already mentioned am new to both elasticsearch and Moqui.

**Comment by jonesde** [comment]
Fetch data from where, ElasticSearch or a relational database?

This is such a broad question that about all I can do is refer you to the documentation:

http://moqui.org/MakingAppsWithMoqui-1.0.pdf

For the most part with ElasticSearch you would use its API directly (and BTW, that link you included has nothing to do with Moqui, it is purely an ElasticSearch thing), though there are some search services that use ElasticSearch.

**Comment by sskmail14** [comment]
Thanks @jonesde 
API Call works fine through ajax call but having an issue that I cant able to get the response when I use the service of Moqui

### Moqui Service Call
```
 <service-call name="org.moqui.impl.EntityServices.search#DataDocuments"
 						out-map="esTest" in-map="context + [indexName:'first_es_index',documentType:'jdbc',queryString:'_id:PFD-43831']"/>

<log level="warn" message="===>>>Elastic context is  -  ${esTest}" /> 

```

### Response of the Log for Moqui Service Call

` ===>>>Elastic context is  -  [documentListPageSize:20, documentListPageRangeHigh:0, documentList:[], documentListPageMaxIndex:0, documentListPageRangeLow:1, documentListCount:0, documentListPageIndex:0]`

### API Call
Am getting the Response from the Elastic Search using Browser from the below URL
[http://localhost:9200/first_es_index/_search?q=_id:PFD-43831&pretty=true](http://localhost:9200/first_es_index/_search?q=_id:PFD-43831&pretty=true)
### Response from the browser
```
{
  "took" : 30,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "first_es_index",
      "_type" : "jdbc",
      "_id" : "PFD-43831",
      "_score" : 1.0,
      "_source":{"PRODUCT_ID":"PFD-43831","PSEUDO_ID":"PFD-43831","PRODUCT_TYPE_ENUM_ID":null,"PRODUCT_CLASS_ENUM_ID":"AVINarcoticsNo","ASSET_TYPE_ENUM_ID":null,"ASSET_CLASS_ENUM_ID":null,"STATUS_ID":"AVIContinue","PRODUCT_NAME":"MEMORVITON Jarabe","DESCRIPTION":null,"COMMENTS":null,"SALES_INTRODUCTION_DATE":null,"SALES_DISCONTINUATION_DATE":null,"SALES_DISC_WHEN_NOT_AVAIL":null,"SUPPORT_DISCONTINUATION_DATE":null,"REQUIRE_INVENTORY":null,"REQUIREMENT_METHOD_ENUM_ID":null,"CHARGE_SHIPPING":null,"IN_SHIPPING_BOX":null,"DEFAULT_SHIPMENT_BOX_TYPE_ID":null,"TAXABLE":null,"TAX_CODE":null,"RETURNABLE":null,"AMOUNT_UOM_ID":null,"AMOUNT_FIXED":null,"AMOUNT_REQUIRE":null,"ORIGIN_GEO_ID":null,"BILL_OF_MATERIAL_LEVEL":null,"MANUFACTURER":"Farmacia y DroguerIa Pharma Heinker","AVI_ACTIVE_INGREDIENT":"ACIDO GLUTAMICO, CALCIO, CLORHIDRATO DE PIRIDOXINA, CLORHIDRATO DE TIAMINA, FOSFORO, PANTOTENATO CALCICO","AVI_PRODUCT_CODE":"PFD-43831","AVI_APPROVAL_STATUS":"AVIAccepted","AVI_MINIMUM_QUANTITY":72,"REQUEST_DATE":null,"LAST_UPDATED_STAMP":"2016-08-22T19:34:53.000+05:30"}
    } ]
  }
}
```
