### ISSUE TITLE
Value of  field of `date-time` type in index seems has timezone issue

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-elasticsearch#3]
I have emplPostion entity set up with DataDocument, it has `fromDate` and `thruDate` field

I set `thruDate` of one record with `2017-02-07 11:00:41.158` (timestamp `1486436441188`) at my local time with `ec.user.nowTimestap`. Then I search with query that thruDate > timestamp `1486436871272` which is `2/7/2017, 11:07:51` my local time,  but it still returned. If I search with query that thruDate > string `2017-02-07T11:07:51`, then the record is not returned. 

I guess it is caused by index date type field with wrong timezone. There might be a conversion when get thruDate from entity, but provide it to elastic search for index as string, then elastic search convert it to with UTC timezone

Elastic Search internally stores date type as long value in index which should be a timestamp. If there was above conversion, probably it is better to index it with timestamp

**Comment by shendepu** [comment]
This issue has be solved by commit a052dc4d50421075120806d23781450dcc0a32ee

**Comment by jonesde** [comment]
Thanks, I forgot there was an issue here on this topic.
